# Generated by Django 3.1.1 on 2020-09-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=180)),
                ('message_type', models.CharField(choices=[('B', 'Boast'), ('R', 'Roast')], max_length=1)),
            ],
        ),
    ]
